// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.SoapApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Library.SoapApi.Db.Entities.tauthor", b =>
                {
                    b.Property<int>("nAuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cSurname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("nAuthorID");

                    b.ToTable("tauthor");
                });

            modelBuilder.Entity("Library.SoapApi.Db.Entities.tbook", b =>
                {
                    b.Property<int>("nBookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("nAuthorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nPublishingCompanyID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("nPublishingYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("nBookID");

                    b.ToTable("tbook");
                });

            modelBuilder.Entity("Library.SoapApi.Db.Entities.tpublishingcompany", b =>
                {
                    b.Property<int>("nPublishingCompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("nPublishingCompanyID");

                    b.ToTable("tpublishingcompany");
                });
#pragma warning restore 612, 618
        }
    }
}
